### ISSUE TITLE
-root flag

### ISSUE THREAD

**Issue by buchanri** [jacksonfelgenhauer/TreeMix#1]
Hello! I'm using your vcf2treemix script but when I add the root flag, I get the error message 
```./vcf2treemix.sh species_group_1_H1_11_31_2_S173_L002_noNa.treemix.vcf.gz feild.clust```
```#run treemix
treemix -i species_group_1_H1_11_31_2_S173_L002_noNa.treemix.frq.gz -m 1 -o ./m1/${FILE}_noNa.treemix_1 -bootstrap -k 500 -root DomRepoutgroup > treemix_1_log
ERROR in placing root: no clade DomRepoutgroup
```
I'm not sure if I'm specifying correctly. I'm basing it off the population I give my samples In the .clust file.
For example my .clust has the form
```
name\tname\tDomRepoutgroup
name\tname\tChina
name\tname\tDomRepoutgroup
name\tname\tIndia
.
.
.
```
Should I be using those names as what I want my root to be?
Thank you for any guidance.

**Comment by jacksonfw** [comment]
Hi, that seems unusual as I'm also using root flag in my analysis. I would suggest double-checking the `.clust` file to make sure that it is properly name as “DomRepoutgroup" 

Each line in the `.clust` file should have a tab between fields, like example below:
```shell
ind_name    sample_name    pop_name
``` 

To further confirm if "DomRepoutgroup" appear as population name from vcf2treemix output, you can run this command:
`zcat species_group_1_H1_11_31_2_S173_L002_noNa.treemix.frq.gz | less`

If this still doesn't solve the issue, I would suggest to try different population as the root or removing the root flag entirely to see if the analysis runs successfully. This way, you can confirm that if "DomRepoutgroup" shows up in the resulting plot.

**Comment by buchanri** [comment]
I did `zcat species_group_1_H1_11_31_2_S173_L002_noNa.treemix.frq.gz | less` and I did in fact have a typo. Thank you for your help!
